// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sea/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreatePoolPair struct {
	Creator     string                                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	AlphaDenom  string                                 `protobuf:"bytes,2,opt,name=alphaDenom,proto3" json:"alphaDenom,omitempty"`
	AlphaAmount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=alphaAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"alphaAmount"`
	BetaDenom   string                                 `protobuf:"bytes,4,opt,name=betaDenom,proto3" json:"betaDenom,omitempty"`
	BetaAmount  github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=betaAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"betaAmount"`
	ShareAmount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,6,opt,name=shareAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"shareAmount"`
	SwapFee     github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,7,opt,name=swapFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"swapFee"`
	ExitFee     github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,8,opt,name=exitFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"exitFee"`
}

func (m *MsgCreatePoolPair) Reset()         { *m = MsgCreatePoolPair{} }
func (m *MsgCreatePoolPair) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePoolPair) ProtoMessage()    {}
func (*MsgCreatePoolPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_9364a1db84fd5f0e, []int{0}
}
func (m *MsgCreatePoolPair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePoolPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePoolPair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePoolPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePoolPair.Merge(m, src)
}
func (m *MsgCreatePoolPair) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePoolPair) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePoolPair.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePoolPair proto.InternalMessageInfo

func (m *MsgCreatePoolPair) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreatePoolPair) GetAlphaDenom() string {
	if m != nil {
		return m.AlphaDenom
	}
	return ""
}

func (m *MsgCreatePoolPair) GetBetaDenom() string {
	if m != nil {
		return m.BetaDenom
	}
	return ""
}

type MsgCreatePoolPairResponse struct {
}

func (m *MsgCreatePoolPairResponse) Reset()         { *m = MsgCreatePoolPairResponse{} }
func (m *MsgCreatePoolPairResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePoolPairResponse) ProtoMessage()    {}
func (*MsgCreatePoolPairResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9364a1db84fd5f0e, []int{1}
}
func (m *MsgCreatePoolPairResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePoolPairResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePoolPairResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePoolPairResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePoolPairResponse.Merge(m, src)
}
func (m *MsgCreatePoolPairResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePoolPairResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePoolPairResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePoolPairResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreatePoolPair)(nil), "VelaChain.pontus.sea.MsgCreatePoolPair")
	proto.RegisterType((*MsgCreatePoolPairResponse)(nil), "VelaChain.pontus.sea.MsgCreatePoolPairResponse")
}

func init() { proto.RegisterFile("sea/tx.proto", fileDescriptor_9364a1db84fd5f0e) }

var fileDescriptor_9364a1db84fd5f0e = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0xdb, 0x8f, 0x4f, 0x90, 0xd1, 0x98, 0x38, 0x61, 0x51, 0xd1, 0x14, 0xc3, 0x42, 0xdc,
	0x38, 0x93, 0xe8, 0x13, 0xf0, 0x27, 0x46, 0x17, 0x18, 0xd2, 0x85, 0x0b, 0x77, 0x43, 0xbd, 0x69,
	0xab, 0xb4, 0xb7, 0x76, 0x86, 0x88, 0x6f, 0xe1, 0x63, 0xb1, 0x64, 0x69, 0x5c, 0x10, 0x03, 0x8f,
	0xe0, 0x0b, 0x98, 0x29, 0x45, 0x1b, 0x71, 0xa1, 0xac, 0xda, 0x7b, 0x7b, 0xee, 0xef, 0xdc, 0x9b,
	0x1e, 0xb2, 0x2d, 0x41, 0x70, 0x35, 0x62, 0x71, 0x82, 0x0a, 0x69, 0xe5, 0x1a, 0x06, 0xa2, 0xed,
	0x8b, 0x20, 0x62, 0x31, 0x46, 0x6a, 0x28, 0x99, 0x04, 0x51, 0xad, 0x78, 0xe8, 0x61, 0x2a, 0xe0,
	0xfa, 0x6d, 0xa1, 0xad, 0xbf, 0x17, 0xc8, 0x6e, 0x57, 0x7a, 0xed, 0x04, 0x84, 0x82, 0x1e, 0xe2,
	0xa0, 0x27, 0x82, 0x84, 0x5a, 0xa4, 0xe4, 0xea, 0x0e, 0x26, 0x96, 0x79, 0x68, 0x1e, 0x97, 0x9d,
	0x65, 0x49, 0x6d, 0x42, 0xc4, 0x20, 0xf6, 0x45, 0x07, 0x22, 0x0c, 0xad, 0x7f, 0xe9, 0xc7, 0x5c,
	0x87, 0xf6, 0xc8, 0x56, 0x5a, 0x35, 0x43, 0x1c, 0x46, 0xca, 0x2a, 0x68, 0x41, 0x8b, 0x8d, 0xa7,
	0x35, 0xe3, 0x75, 0x5a, 0x3b, 0xf2, 0x02, 0xe5, 0x0f, 0xfb, 0xcc, 0xc5, 0x90, 0xbb, 0x28, 0x43,
	0x94, 0xd9, 0xe3, 0x44, 0xde, 0xde, 0x73, 0xf5, 0x14, 0x83, 0x64, 0x97, 0x91, 0x72, 0xf2, 0x08,
	0x7a, 0x40, 0xca, 0x7d, 0x50, 0x99, 0xe1, 0xff, 0xd4, 0xf0, 0xab, 0x41, 0xaf, 0x08, 0xd1, 0x45,
	0x66, 0xb7, 0xb1, 0x96, 0x5d, 0x8e, 0xa0, 0xf7, 0x97, 0xbe, 0x48, 0x20, 0x03, 0x16, 0xd7, 0xdb,
	0x3f, 0x87, 0xa0, 0x17, 0xa4, 0x24, 0x1f, 0x45, 0x7c, 0x0e, 0x60, 0x95, 0xfe, 0x4c, 0xeb, 0x80,
	0xeb, 0x2c, 0xc7, 0x35, 0x09, 0x46, 0x81, 0xd2, 0xa4, 0xcd, 0xf5, 0x48, 0xd9, 0x78, 0x7d, 0x9f,
	0xec, 0xad, 0xfc, 0x74, 0x07, 0x64, 0x8c, 0x91, 0x84, 0xd3, 0x07, 0x52, 0xe8, 0x4a, 0x8f, 0xde,
	0x91, 0x9d, 0x6f, 0xa9, 0x68, 0xb0, 0x9f, 0x82, 0xc5, 0x56, 0x48, 0x55, 0xfe, 0x4b, 0xe1, 0xd2,
	0xb2, 0xd5, 0x1c, 0xcf, 0x6c, 0x73, 0x32, 0xb3, 0xcd, 0xb7, 0x99, 0x6d, 0x3e, 0xcf, 0x6d, 0x63,
	0x32, 0xb7, 0x8d, 0x97, 0xb9, 0x6d, 0xdc, 0x34, 0x72, 0xa7, 0x7d, 0x42, 0xf9, 0x02, 0xca, 0x47,
	0x3c, 0xcd, 0xbd, 0xbe, 0xaf, 0x5f, 0x4c, 0xf3, 0x7c, 0xf6, 0x11, 0x00, 0x00, 0xff, 0xff, 0x40,
	0x51, 0xce, 0xab, 0x0b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreatePoolPair(ctx context.Context, in *MsgCreatePoolPair, opts ...grpc.CallOption) (*MsgCreatePoolPairResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreatePoolPair(ctx context.Context, in *MsgCreatePoolPair, opts ...grpc.CallOption) (*MsgCreatePoolPairResponse, error) {
	out := new(MsgCreatePoolPairResponse)
	err := c.cc.Invoke(ctx, "/VelaChain.pontus.sea.Msg/CreatePoolPair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreatePoolPair(context.Context, *MsgCreatePoolPair) (*MsgCreatePoolPairResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreatePoolPair(ctx context.Context, req *MsgCreatePoolPair) (*MsgCreatePoolPairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePoolPair not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreatePoolPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePoolPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePoolPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VelaChain.pontus.sea.Msg/CreatePoolPair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePoolPair(ctx, req.(*MsgCreatePoolPair))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VelaChain.pontus.sea.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePoolPair",
			Handler:    _Msg_CreatePoolPair_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sea/tx.proto",
}

func (m *MsgCreatePoolPair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePoolPair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePoolPair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ExitFee.Size()
		i -= size
		if _, err := m.ExitFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.SwapFee.Size()
		i -= size
		if _, err := m.SwapFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.ShareAmount.Size()
		i -= size
		if _, err := m.ShareAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.BetaAmount.Size()
		i -= size
		if _, err := m.BetaAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.BetaDenom) > 0 {
		i -= len(m.BetaDenom)
		copy(dAtA[i:], m.BetaDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BetaDenom)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.AlphaAmount.Size()
		i -= size
		if _, err := m.AlphaAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.AlphaDenom) > 0 {
		i -= len(m.AlphaDenom)
		copy(dAtA[i:], m.AlphaDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AlphaDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePoolPairResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePoolPairResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePoolPairResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreatePoolPair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AlphaDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.AlphaAmount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.BetaDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.BetaAmount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.ShareAmount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.SwapFee.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.ExitFee.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCreatePoolPairResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreatePoolPair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePoolPair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePoolPair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlphaDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AlphaDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlphaAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AlphaAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetaDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BetaDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetaAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BetaAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ShareAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SwapFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExitFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExitFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePoolPairResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePoolPairResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePoolPairResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
